// Domain types come from the daemon's own SDL via the unified codegen
// (`runtime/schemas/operator.graphql` → `@angee/gql/operator/types`); the console
// never hand-maintains them. The daemon operation documents are generated by the
// same pass under `@angee/gql/operator`. This module re-exports the schema shapes
// the panes render and adds the frontend-only `OperatorSnapshot`: the daemon
// exposes its state as separate root query fields, not one object, so the console
// aggregates the roots each pane needs into a single snapshot.
import type { DocumentData, DocumentVariables } from "@angee/refine";

import type {
  SNAPSHOT_QUERY,
  STACK_SNAPSHOT_SUBSCRIPTION,
} from "./documents.daemon";

export type {
  ServiceState,
  JobState,
  SourceState,
  WorkspaceSourceStatus,
  WorkspaceRef,
  WorkspaceStatus,
  TemplateDescriptor,
  TemplateInputDescriptor,
  SecretRef,
  StackStatus,
  GitOpsTopology,
  GitOpsLink,
  GitOpsSummary,
  CommitRef,
  MutationResult,
  WorkspaceCreateInput,
  KeyValueInput,
} from "@angee/gql/operator/types";

import type {
  ServiceState,
  JobState,
  SourceState,
  WorkspaceRef,
  TemplateDescriptor,
  SecretRef,
  StackStatus,
  GitOpsTopology,
  MutationResult,
} from "@angee/gql/operator/types";

export interface OperatorConnectionInfo {
  endpoint: string;
  token: string;
}

/**
 * The console snapshot: one daemon query selecting the root fields each pane
 * needs (the daemon has no single snapshot object). `health` is the daemon's
 * `MutationResult` health probe; `stack` carries the stack identity.
 */
export interface OperatorSnapshot {
  health: MutationResult | null;
  stack: Pick<StackStatus, "root" | "name"> | null;
  services: readonly ServiceState[];
  jobs: readonly JobState[];
  sources: readonly SourceState[];
  workspaces: readonly WorkspaceRef[];
  templates: readonly TemplateDescriptor[];
  secrets: readonly SecretRef[];
  gitOps: Pick<GitOpsTopology, "root" | "name" | "summary" | "links"> | null;
}

/** Raw snapshot-query result: each root is omitted unless its `@include` is on. */
export type OperatorSnapshotQueryData = DocumentData<typeof SNAPSHOT_QUERY>;

/** The snapshot query's `@include` toggles — one per pane (`$wantOverview`...). */
export type OperatorSnapshotQueryVariables =
  DocumentVariables<typeof SNAPSHOT_QUERY>;

/**
 * The live snapshot push: `onStackSnapshotChange` carries the daemon's aggregate
 * `StackSnapshot` (the generated type). It selects every root, so all are present
 * on each push; its non-null arrays are assignable to the query's nullable roots,
 * so {@link snapshotFromQueryData} consumes either source.
 */
export type OperatorSnapshotSubscriptionData = DocumentData<
  typeof STACK_SNAPSHOT_SUBSCRIPTION
>;

/** Which panes' data to fetch — maps to the snapshot query's `@include` flags. */
export interface OperatorSnapshotSections {
  overview?: boolean;
  services?: boolean;
  workspaces?: boolean;
  sources?: boolean;
  gitOps?: boolean;
  operations?: boolean;
  templates?: boolean;
  secrets?: boolean;
}
