# Generated by Django 6.0.5 on 2026-05-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("source_addon", models.CharField(max_length=200)),
                ("source_path", models.CharField(max_length=300)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("master", "Master"),
                            ("install", "Install"),
                            ("demo", "Demo"),
                        ],
                        max_length=40,
                    ),
                ),
                ("xref", models.CharField(max_length=160)),
                ("content_hash", models.CharField(max_length=71)),
                ("target_model", models.CharField(max_length=120)),
                ("target_id", models.CharField(blank=True, default="", max_length=120)),
                ("loaded_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("source_addon", "source_path", "xref", "target_model"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_addon", "source_path", "xref", "target_model"),
                        name="base_resource_source_target",
                    )
                ],
            },
        ),
    ]
